In [25]:
import pandas as pd

df= pd.read_excel("/content/REGISTRO_RECLAMOS.xlsx")
df.head(3)

,NRO RECLAMO,MEDIO RECEPCION,FECHA RECEPCION,HORA RECEPCION,LUG. EXPEDIDO,CATEGORIA,MOTIVO_RECLAMO,DETALLE,FECHA RESPUESTA,HORA RESPUESTA,POSICION EMPRESA,MEDIO DE RESPUESTA
0,300,llamada,01 09 2025,8 24 00,LIMA,RE_C1,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA...,2025-09-02,16:16:00,NO JUSTIFICADO,llamada
1,301,llamada,01 09 2025,8 28 00,LIMA,RE_C1,NUEVA CONEXIÓN,CONSUMIDORA INDICA QUE SOLICITÓ UN SERVICIO NU...,2025-09-01,11:14:00,JUSTIFICADO,llamada
2,302,Presencialmente,01 09 2025,8 33 00,LIMA,GE_BT,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA ...,2025-09-01,11:09:00,NO JUSTIFICADO,llamada

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NRO RECLAMO         2534 non-null   int64
 1   MEDIO RECEPCION     2534 non-null   object
 2   FECHA RECEPCION     2534 non-null   object
 3   HORA RECEPCION      2534 non-null   object
 4   LUG. EXPEDIDO       2534 non-null   object
 5   CATEGORIA           2534 non-null   object
 6   MOTIVO_RECLAMO      2534 non-null   object
 7   DETALLE             2534 non-null   object
 8   FECHA RESPUESTA     2534 non-null   datetime64[ns]
 9   HORA RESPUESTA      2534 non-null   object
 10  POSICION EMPRESA    2534 non-null   object
 11  MEDIO DE RESPUESTA  2532 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 237.7+ KB

In [27]:
#Lo que haremos es concatenar 2 columnas y mostrar
df["fecha de recepcion"]= df["FECHA RECEPCION"].astype(str) + " " + df["HORA RECEPCION"].astype(str)

df["fecha de respuesta"]= df["FECHA RESPUESTA"].astype(str) + " " + df["HORA RESPUESTA"].astype(str)
df.head(3)

,NRO RECLAMO,MEDIO RECEPCION,FECHA RECEPCION,HORA RECEPCION,LUG. EXPEDIDO,CATEGORIA,MOTIVO_RECLAMO,DETALLE,FECHA RESPUESTA,HORA RESPUESTA,POSICION EMPRESA,MEDIO DE RESPUESTA,fecha de recepcion,fecha de respuesta
0,300,llamada,01 09 2025,8 24 00,LIMA,RE_C1,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA...,2025-09-02,16:16:00,NO JUSTIFICADO,llamada,01 09 2025 8 24 00,2025-09-02 16:16:00
1,301,llamada,01 09 2025,8 28 00,LIMA,RE_C1,NUEVA CONEXIÓN,CONSUMIDORA INDICA QUE SOLICITÓ UN SERVICIO NU...,2025-09-01,11:14:00,JUSTIFICADO,llamada,01 09 2025 8 28 00,2025-09-01 11:14:00
2,302,Presencialmente,01 09 2025,8 33 00,LIMA,GE_BT,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA ...,2025-09-01,11:09:00,NO JUSTIFICADO,llamada,01 09 2025 8 33 00,2025-09-01 11:09:00

In [28]:
#borraremos las columnas que ya no se usaran

df.drop(["FECHA RECEPCION","HORA RECEPCION","FECHA RESPUESTA","HORA RESPUESTA"], axis=1, inplace=True)
df.head(3)

,NRO RECLAMO,MEDIO RECEPCION,LUG. EXPEDIDO,CATEGORIA,MOTIVO_RECLAMO,DETALLE,POSICION EMPRESA,MEDIO DE RESPUESTA,fecha de recepcion,fecha de respuesta
0,300,llamada,LIMA,RE_C1,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA...,NO JUSTIFICADO,llamada,01 09 2025 8 24 00,2025-09-02 16:16:00
1,301,llamada,LIMA,RE_C1,NUEVA CONEXIÓN,CONSUMIDORA INDICA QUE SOLICITÓ UN SERVICIO NU...,JUSTIFICADO,llamada,01 09 2025 8 28 00,2025-09-01 11:14:00
2,302,Presencialmente,LIMA,GE_BT,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA ...,NO JUSTIFICADO,llamada,01 09 2025 8 33 00,2025-09-01 11:09:00

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NRO RECLAMO         2534 non-null   int64
 1   MEDIO RECEPCION     2534 non-null   object
 2   LUG. EXPEDIDO       2534 non-null   object
 3   CATEGORIA           2534 non-null   object
 4   MOTIVO_RECLAMO      2534 non-null   object
 5   DETALLE             2534 non-null   object
 6   POSICION EMPRESA    2534 non-null   object
 7   MEDIO DE RESPUESTA  2532 non-null   object
 8   fecha de recepcion  2534 non-null   object
 9   fecha de respuesta  2534 non-null   object
dtypes: int64(1), object(9)
memory usage: 198.1+ KB

In [30]:
#ahora debemos convertir el tipo de objetc a datatime
df["fecha de recepcion"] = pd.to_datetime(df["fecha de recepcion"], format="%d %m %Y %H %M %S")
df["fecha de respuesta"] = pd.to_datetime(df["fecha de respuesta"], format="%Y-%m-%d %H:%M:%S")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NRO RECLAMO         2534 non-null   int64
 1   MEDIO RECEPCION     2534 non-null   object
 2   LUG. EXPEDIDO       2534 non-null   object
 3   CATEGORIA           2534 non-null   object
 4   MOTIVO_RECLAMO      2534 non-null   object
 5   DETALLE             2534 non-null   object
 6   POSICION EMPRESA    2534 non-null   object
 7   MEDIO DE RESPUESTA  2532 non-null   object
 8   fecha de recepcion  2534 non-null   datetime64[ns]
 9   fecha de respuesta  2534 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(7)
memory usage: 198.1+ KB

In [31]:
df["tiempo de atencion"] = df["fecha de respuesta"] - df["fecha de recepcion"]
df.head(3)

,NRO RECLAMO,MEDIO RECEPCION,LUG. EXPEDIDO,CATEGORIA,MOTIVO_RECLAMO,DETALLE,POSICION EMPRESA,MEDIO DE RESPUESTA,fecha de recepcion,fecha de respuesta,tiempo de atencion
0,300,llamada,LIMA,RE_C1,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA...,NO JUSTIFICADO,llamada,2025-09-01 08:24:00,2025-09-02 16:16:00,1 days 07:52:00
1,301,llamada,LIMA,RE_C1,NUEVA CONEXIÓN,CONSUMIDORA INDICA QUE SOLICITÓ UN SERVICIO NU...,JUSTIFICADO,llamada,2025-09-01 08:28:00,2025-09-01 11:14:00,0 days 02:46:00
2,302,Presencialmente,LIMA,GE_BT,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA ...,NO JUSTIFICADO,llamada,2025-09-01 08:33:00,2025-09-01 11:09:00,0 days 02:36:00

In [32]:
df["respuesta en seg"] = df["tiempo de atencion"].dt.total_seconds()
df.head(3)
#aqui ya tenemos que tardo el cliente en ser atendido en dias tanto como en segundos

,NRO RECLAMO,MEDIO RECEPCION,LUG. EXPEDIDO,CATEGORIA,MOTIVO_RECLAMO,DETALLE,POSICION EMPRESA,MEDIO DE RESPUESTA,fecha de recepcion,fecha de respuesta,tiempo de atencion,respuesta en seg
0,300,llamada,LIMA,RE_C1,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA...,NO JUSTIFICADO,llamada,2025-09-01 08:24:00,2025-09-02 16:16:00,1 days 07:52:00,114720.0
1,301,llamada,LIMA,RE_C1,NUEVA CONEXIÓN,CONSUMIDORA INDICA QUE SOLICITÓ UN SERVICIO NU...,JUSTIFICADO,llamada,2025-09-01 08:28:00,2025-09-01 11:14:00,0 days 02:46:00,9960.0
2,302,Presencialmente,LIMA,GE_BT,EXCESIVO CONSUMO,CONSUMIDOR INDICA QUE EXISTE INCREMENTO EN LA ...,NO JUSTIFICADO,llamada,2025-09-01 08:33:00,2025-09-01 11:09:00,0 days 02:36:00,9360.0

In [33]:
df.describe()
#aqui puedo ver que la media es 135117,7 segundos,lo cual sigue siendo un valor alto de 37 horas para atender un reclamo
#tomaremos un reclamo rapido que sea menor a

,NRO RECLAMO,fecha de recepcion,fecha de respuesta,tiempo de atencion,respuesta en seg
count,2534.000000,2534,2534,2534,2.534000e+03
mean,1568.843725,2025-09-17 07:15:12.786108928,2025-09-18 20:47:10.489344768,1 days 13:31:57.703235990,1.351177e+05
min,300.000000,2025-09-01 08:24:00,2025-09-01 09:48:00,0 days 00:01:00,6.000000e+01
25%,933.250000,2025-09-09 10:55:00,2025-09-10 15:27:30,0 days 04:23:15,1.579500e+04
50%,1567.500000,2025-09-18 10:19:00,2025-09-19 15:56:00,1 days 02:42:30,9.615000e+04
75%,2204.750000,2025-09-25 12:26:15,2025-09-26 11:59:45,2 days 02:53:45,1.832250e+05
max,2840.000000,2025-09-30 20:09:00,2025-10-15 15:21:00,19 days 21:12:00,1.717920e+06
std,733.843055,NaN,NaN,1 days 17:51:53.831188714,1.507138e+05

In [34]:
conteo = (df["respuesta en seg"] < 3600).value_counts()
print(conteo)
#Entonces los reclamos mas rapidos segun mi criterio fueron contestadas en menos de una hora (3600 segundos) un total de 336 personas

respuesta en seg
False    2198
True      336
Name: count, dtype: int64

In [35]:
caterogias = df["CATEGORIA"].unique()
print(caterogias)

['RE_C1' 'GE_BT' 'RE_C2' 'RE_C4' 'GE_C4' 'GE_C5' 'RE_C5' 'I_C1'
 'MINERA_C2' 'GE_C2' 'COOP' 'RE_C3' 'GE_C1' 'GE_C3' 'I_C2']

In [36]:
conteo = df["CATEGORIA"].value_counts()
print(conteo)
# Se puede aprecion que los reclamos se dieron mas en la categoria RE_C1

CATEGORIA
RE_C1        2071
GE_C4         196
RE_C2          97
RE_C4          92
GE_C5          22
MINERA_C2      17
GE_BT          14
RE_C5           6
I_C1            4
GE_C3           4
GE_C2           3
RE_C3           3
GE_C1           2
I_C2            2
COOP            1
Name: count, dtype: int64

In [37]:
motivo = df["MOTIVO_RECLAMO"].unique()
print(motivo)

['EXCESIVO CONSUMO' 'NUEVA CONEXIÓN' 'OTROS DE SOLICITUDES DE SERVICIO'
 'CARGOS INDEBIDOS' 'FACT.O AVISOS DE COBRANZAS NO RECIBIDO'
 'RECONEXIÓN DEMORADA' 'OTROS DE MALA ATENCIÓN' 'ERROR DE LECTURA ACTUAL'
 'SUSPENSIÓN INDEBIDA DEL SERVICIO' 'MAL ESTADO DEL MEDIDOR'
 'OTROS DE FACTURACION' 'ERROR DE PROMEDIO' 'ERROR DE LECTURA ANTERIOR'
 'CORTE INDEBIDO DEL SERVICIO' 'SUSPENSIÓN - MAL TRABAJO OPERATIVO'
 'CAMBIO DE CATEGORIA' 'TARIFACIÓN - CATEGORIA ERRADA'
 'MALA ATENCION EN OFICINAS' 'RECONEXIÓN - MAL TRABAJO OPERATIVO'
 'TRASLADO -DEMORA' 'SUSPENSIONES TEMP./DEFINITIVAS - DEMORA'
 'SUSPENSIÓN - RETIRO INDEBIDO DE MEDIDOR' 'MALA ATENCION EN TERRENO'
 'CORTE - MAL TRABAJO OPERATIVO' 'MALA APLICACIÓN DE RECARGO POR MORA'
 'MALA ATENCION POR TELÉFONO' 'FACT. O AVISOS DE COBRANZAS FUERA TERMINO'
 'FACTURAS NO RECIBIDA' 'RETIRO INDEBIDO DEL MEDIDOR'
 'TRASLADO - MAL TRABAJO OPERATIVO']

In [38]:
conteo_motivos = df["MOTIVO_RECLAMO"].value_counts()
print(conteo_motivos)
#El motivo con mayor numero es el EXCESIVO CONSUMO

MOTIVO_RECLAMO
EXCESIVO CONSUMO                             1125
RECONEXIÓN DEMORADA                           533
FACT.O AVISOS DE COBRANZAS NO RECIBIDO        169
NUEVA CONEXIÓN                                129
ERROR DE PROMEDIO                             113
CARGOS INDEBIDOS                               85
ERROR DE LECTURA ACTUAL                        77
OTROS DE MALA ATENCIÓN                         65
MAL ESTADO DEL MEDIDOR                         49
OTROS DE FACTURACION                           25
CORTE INDEBIDO DEL SERVICIO                    20
OTROS DE SOLICITUDES DE SERVICIO               18
SUSPENSIÓN INDEBIDA DEL SERVICIO               16
CAMBIO DE CATEGORIA                            16
SUSPENSIÓN - RETIRO INDEBIDO DE MEDIDOR        16
RECONEXIÓN - MAL TRABAJO OPERATIVO             16
TRASLADO -DEMORA                               14
ERROR DE LECTURA ANTERIOR                      13
MALA ATENCION EN TERRENO                        6
CORTE - MAL TRABAJO OPERATIVO                   5
SUSPENSIÓN - MAL TRABAJO OPERATIVO              4
MALA ATENCION EN OFICINAS                       4
RETIRO INDEBIDO DEL MEDIDOR                     4
TARIFACIÓN - CATEGORIA ERRADA                   3
SUSPENSIONES TEMP./DEFINITIVAS - DEMORA         2
MALA APLICACIÓN DE RECARGO POR MORA             2
FACTURAS NO RECIBIDA                            2
MALA ATENCION POR TELÉFONO                      1
FACT. O AVISOS DE COBRANZAS FUERA TERMINO       1
TRASLADO - MAL TRABAJO OPERATIVO                1
Name: count, dtype: int64

In [42]:
maximos_por_reclamo = df.groupby("CATEGORIA")["respuesta en seg"].max()
print(maximos_por_reclamo)
#entonces el RE_C1 fue la categoria que demoro mas tiempo en ser atendido

CATEGORIA
RE_C1        1717920.0
MINERA_C2    1119720.0
RE_C2        1001280.0
GE_C4         965100.0
GE_C5         943200.0
GE_BT         676380.0
GE_C3         615180.0
I_C1          606180.0
RE_C4         441060.0
GE_C2         417780.0
I_C2          406320.0
GE_C1         267240.0
RE_C5         264480.0
RE_C3         114000.0
COOP          107700.0
Name: respuesta en seg, dtype: float64